// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl56y8i_UZuHqHRnbdKXmFJ_WoBaRToFw',
    appId: '1:405829575296:web:a0c3f77fa64690093dbc65',
    messagingSenderId: '405829575296',
    projectId: 'echoproof-50760',
    authDomain: 'echoproof-50760.firebaseapp.com',
    storageBucket: 'echoproof-50760.firebasestorage.app',
    measurementId: 'G-ZKGVGGMFTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1YmiXnhdD8ICBwqQ3ZYczRn6nr99HPM',
    appId: '1:405829575296:android:fd8c69aa88e264323dbc65',
    messagingSenderId: '405829575296',
    projectId: 'echoproof-50760',
    storageBucket: 'echoproof-50760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR712gd0CUjdmk4tq0zfbogP1UxQ0kLGw',
    appId: '1:405829575296:ios:79c86b654baa5f133dbc65',
    messagingSenderId: '405829575296',
    projectId: 'echoproof-50760',
    storageBucket: 'echoproof-50760.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR712gd0CUjdmk4tq0zfbogP1UxQ0kLGw',
    appId: '1:405829575296:ios:79c86b654baa5f133dbc65',
    messagingSenderId: '405829575296',
    projectId: 'echoproof-50760',
    storageBucket: 'echoproof-50760.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
