-- adds solana-related fields to support on-chain features
-- run order: 006 (after 005_ai_metadata)

alter table users_public
  add column if not exists wallet_address text,
  add column if not exists trust_anchor_tx text;

comment on column users_public.wallet_address is
  'solana public key — generated by the app, never entered by user';

comment on column users_public.trust_anchor_tx is
  'solana transaction signature when trust tier was last anchored on-chain';

alter table echoes
  add column if not exists verified_record_tx text,
  add column if not exists verified_record_at  timestamptz;

comment on column echoes.verified_record_tx is
  'solana transaction signature of the permanent verification record';

alter table echo_proofs
  add column if not exists stake_tx      text,
  add column if not exists stake_amount  integer default 0;

comment on column echo_proofs.stake_tx is
  'solana transaction signature of the proof stake transfer';

comment on column echo_proofs.stake_amount is
  'amount staked in lamports (1 SOL = 1000000000 lamports)';

create index if not exists echoes_verified_record_idx
  on echoes(verified_record_tx)
  where verified_record_tx is not null;