// ai slop guard
// @params title optional title text for echo posts
// @params body user written text that should sound human

enum AiSlopSeverity { ok, warn, block }

class AiSlopAssessment {
  const AiSlopAssessment({
    required this.severity,
    required this.score,
    required this.message,
  });

  final AiSlopSeverity severity;
  final int score;
  final String message;

  bool get shouldWarn => severity == AiSlopSeverity.warn;
  bool get isBlocked => severity == AiSlopSeverity.block;
}

abstract final class AiSlopGuard {
  static const _hardBlockPhrases = [
    'as an ai language model',
    'i cannot browse the internet',
    'i do not have personal opinions',
    'generated by chatgpt',
    'written by chatgpt',
    'here is a draft you can use',
    'certainly here',
  ];

  static const _softSignals = [
    'in today\'s digital age',
    'it is important to note',
    'it is worth noting',
    'delve into',
    'in the realm of',
    'ever-evolving landscape',
    'comprehensive guide',
    'game changer',
    'unlock the power',
    'seamlessly integrates',
    'robust solution',
    'cutting-edge',
    'furthermore',
    'moreover',
    'in conclusion',
    'a testament to',
    'plays a crucial role',
    'not only but also',
  ];

  static AiSlopAssessment assess({
    String title = '',
    required String body,
    bool allowShort = true,
  }) {
    final text = '$title\n$body'.trim();
    final normalized = _normalize(text);
    if (normalized.isEmpty) {
      return const AiSlopAssessment(
        severity: AiSlopSeverity.ok,
        score: 0,
        message: '',
      );
    }

    final words = _words(normalized);
    if (allowShort && words.length < 18) {
      final hardShort = _hardBlockPhrases.any(normalized.contains);
      if (!hardShort) {
        return const AiSlopAssessment(
          severity: AiSlopSeverity.ok,
          score: 0,
          message: '',
        );
      }
    }

    var score = 0;
    final hardMatch = _hardBlockPhrases.where(normalized.contains).toList();
    score += hardMatch.length * 6;

    final softMatch = _softSignals.where(normalized.contains).toList();
    score += softMatch.length * 2;

    final sentenceCount = RegExp(r'[.!?]').allMatches(text).length;
    final commaCount = ','.allMatches(text).length;
    final bulletCount = RegExp(
      r'(^|\n)\s*[-*\u2022]\s+',
    ).allMatches(text).length;
    final numberedCount = RegExp(
      r'(^|\n)\s*\d+[.)]\s+',
    ).allMatches(text).length;

    if (words.length > 70 && sentenceCount <= 2) score += 2;
    if (words.length > 120 && commaCount > 10 && sentenceCount < 5) score += 2;
    if (bulletCount + numberedCount >= 5) score += 2;
    if (_hasTemplateRhythm(text)) score += 2;
    if (_genericDensity(words) > 0.18 && words.length > 45) score += 2;

    final hasSpecificity =
        RegExp(r'\b\d{2,}\b').hasMatch(normalized) ||
        normalized.contains('http://') ||
        normalized.contains('https://') ||
        normalized.contains('@') ||
        normalized.contains('#') ||
        RegExp(
          r'\b(i|we|my|our|today|yesterday|tomorrow)\b',
        ).hasMatch(normalized);

    if (!hasSpecificity && words.length > 80) score += 1;

    if (hardMatch.isNotEmpty || score >= 9) {
      return AiSlopAssessment(
        severity: AiSlopSeverity.block,
        score: score.clamp(0, 100),
        message:
            'This reads like generated boilerplate. Rewrite it in your own words before posting.',
      );
    }

    if (score >= 5) {
      return AiSlopAssessment(
        severity: AiSlopSeverity.warn,
        score: score.clamp(0, 100),
        message:
            'This sounds a little generic. Add your own detail so people can judge it fairly.',
      );
    }

    return AiSlopAssessment(
      severity: AiSlopSeverity.ok,
      score: score.clamp(0, 100),
      message: '',
    );
  }

  static String _normalize(String text) {
    return text
        .toLowerCase()
        .replaceAll(RegExp(r'\s+'), ' ')
        .replaceAll(RegExp(r'[“”]'), '"')
        .replaceAll(RegExp(r'[‘’]'), "'")
        .trim();
  }

  static List<String> _words(String text) {
    return RegExp(
      r"[a-z0-9']+",
    ).allMatches(text).map((m) => m.group(0)!).toList();
  }

  static bool _hasTemplateRhythm(String text) {
    final starts = RegExp(
      r'(^|\n)\s*(firstly|secondly|thirdly|overall|finally|in conclusion)\b',
      caseSensitive: false,
    ).allMatches(text);
    return starts.length >= 3;
  }

  static double _genericDensity(List<String> words) {
    if (words.isEmpty) return 0;
    const generic = {
      'important',
      'significant',
      'various',
      'several',
      'numerous',
      'impact',
      'innovative',
      'effective',
      'efficient',
      'solution',
      'solutions',
      'potential',
      'critical',
      'essential',
      'overall',
      'therefore',
      'moreover',
      'furthermore',
    };
    final matches = words.where(generic.contains).length;
    return matches / words.length;
  }
}
